stages:
  - build

.gradle-image: &gradle-image
  image: gradle:5.5-jdk12

build:
  <<: *gradle-image
  stage: build
  variables:
    CLIENT_KEY: $SPOTIFY_CLIENT_KEY
  script:
    - export CLIENT_KEY="$CLIENT_KEY"
    - gradle clean build
  only:
    - master